### ISSUE TITLE
Fix this error when polling for parcel data

### ISSUE THREAD

**Issue by jampez77** [jampez77/Yodel#2]
This error originated from a custom integration.

Logger: custom_components.yodel.coordinator
Source: helpers/update_coordinator.py:354
integration: Yodel (documentation, issues)
First occurred: 01:01:56 (1 occurrences)
Last logged: 01:01:56

Unexpected error fetching Yodel data
Traceback (most recent call last):
  File "/config/custom_components/yodel/coordinator.py", line 107, in _async_update_data
    parcel_data = parcelCoordinator.data.get(CONF_DATA)[CONF_TRACKPARCEL]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yodel/coordinator.py", line 120, in _async_update_data
    raise UnknownError from err
custom_components.yodel.coordinator.UnknownError

**Comment by jampez77** [comment]
This should be fixed in [2024.10.3](https://github.com/jampez77/Yodel/releases/tag/2024.10.3)
